### PR TITLE
Add JMeter 2.13 in /opt/jmeter/

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
Add JMeter 2.13 in /opt/jmeter/

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
Can you review @ydubreuil @ndeloof

**Comment by ndeloof** [comment]
Why put maven into `/usr/share/` and jmeter under `/opt` ? (I don't have any preference, just wonder there's some reason)
LGTM

**Comment by cyrille-leclerc** [comment]
@ndeloof you are right, I have chosen `/opt/` because selenium is under `/opt/` and because I found samples for jmeter using `/opt/` but I could also have chosen `/usr/share`.

I noticed that the .deb package installs under `/usr/share/`, I found other samples using `/opt`.

I preferred to not rely on the .deb to installer a fresher version of jmeter.

**Comment by ydubreuil** [comment]
`/opt` is the "official" LSB location for manually installed tools.

LGTM

**Comment by cyrille-leclerc** [comment]
So I have your blessing? :-)

**Comment by ydubreuil** [comment]
yes, `/opt` is the right choice here

**Pull request merged**
